"""delete column token, cause jarene iku JWT not stored in DB

Revision ID: 4679c3c00785
Revises: 7202c17cbfac
Create Date: 2020-08-24 12:31:33.325479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4679c3c00785'
down_revision = '7202c17cbfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
